{{- if .Values.backup.enabled }}
apiVersion: {{ include "frontend.cron.api-version" . | trim }}
kind: CronJob
metadata:
  name: {{ .Release.Name }}-backup
  labels:
    cronjob-type: backup
spec:
  {{- if .Values.timezone }}
  {{- if eq ( include "frontend.cron.timezone-support" . ) "true" }}
  timeZone: {{ .Values.timezone | quote }}
  {{- end }}
  {{- end }}
  schedule: {{ .Values.backup.schedule | replace "~" (randNumeric 1) | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 3600
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      activeDeadlineSeconds: 7200
      backoffLimit: 2
      template:
        spec:
          enableServiceLinks: false
          initContainers:
            - name: backup-linking
              image: wunderio/silta-rsync:v1
              command: ["/bin/bash", "-c"]
              args:
                - |
                  {{- include "frontend.backup.create-destination-path" . | nindent 18 }}
              volumeMounts:
                {{- range $index, $mount := $.Values.mounts }}
                {{- if eq $mount.enabled true }}
                - name: frontend-{{ $index }}
                  mountPath: /values_mounts/{{ $index }}
                {{- end }}
                {{- end }}
                - name: {{ .Release.Name }}-backup
                  mountPath: /backup_archive
                - mountPath: /backups
                  name: shared-data
          containers:
          - name: backup
            image: wunderio/silta-rsync:v1
            volumeMounts:
              {{- range $index, $mount := $.Values.mounts -}}
              {{- if eq $mount.enabled true }}
              - name: frontend-{{ $index }}
                mountPath: /values_mounts/{{ $index }}
              {{- end }}
              {{- end }}
              - name: {{ $.Release.Name }}-backup
                mountPath: /backup_archive
              - mountPath: /backups
                name: shared-data
            command: ["/bin/bash", "-c"]
            args:
              - |
                {{- include "frontend.backup.copy-mounts" . | nindent 16 }}

                # Delete old backups
                echo "Removing backups older than {{ .Values.backup.retention }} days"

                # Can't locate directories based on mtime due to storage backend limitations, 
                # Using folder name for time selection. 
                retention_time=$(date -d "{{ .Values.backup.retention }} days ago" +%s)
                                
                find /backup_archive -type d -mindepth 1 -maxdepth 1 -print \
                | grep -E '/[0-9-]+$' \
                | while read -r dir
                do

                  # convert dir name into timestamp
                  stamp="$(echo "$dir" | sed -re 's%.+/(.+)-(.+)-(.+)-(.+)-(.+)-(.+)$%\1-\2-\3 \4:\5:\6%')"
                  stamp="$(date -d "$stamp" '+%s')" || continue
                  
                  # jump out of the execution block if the directory more recent than retention time
                  if [[ "$stamp" -gt "$retention_time" ]]; then
                    continue
                  fi

                  # All checks have passed and we can remove the directory.
                  echo "Removing directory: $dir"
                  rm -rf "$dir"

                done
                
          {{- range $index, $service := .Values.services }}
          {{- $backupCommand := "" }}
          {{- if (hasKey $service "backup") }}
          {{- if (hasKey $service.backup "command") }}
          {{- $backupCommand = $service.backup.command }}
          {{- end }}
          {{- end }}
          {{- if $backupCommand }}
          - name: {{ $index }}
            image: {{ $service.image | quote }}
            command: ["/bin/bash", "-c"]
            args:
              - |
                {{- $backupCommand | nindent 16 }}
            env:
            {{- include "services.env" (dict "Values" $.Values "Release" $.Release "service" $service) | nindent 12 }}
            {{- range $key, $val := $service.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            volumeMounts:
              - name: {{ $.Release.Name }}-backup
                mountPath: /backup_archive
              - mountPath: /backups
                name: shared-data
              {{ if $service.mounts }}
              {{- range $index, $mountName := $service.mounts -}}
              {{ $mount := (index $.Values.mounts $mountName) }}
              {{- if eq $mount.enabled true }}
              - name: frontend-{{ $mountName }}
                mountPath: {{ $mount.mountPath }}
              {{- end }}
              {{- end }}
              {{- end }}
          {{- end }}
          {{- end }}
          restartPolicy: Never
          volumes:
            - name: shared-data
              emptyDir:
                sizeLimit: 10M
            {{- range $index, $service := .Values.services }}
            {{- if $service.mounts -}}
            {{- range $index, $mountName := $service.mounts -}}
            {{ $mount := (index $.Values.mounts $mountName) }}
            {{- if eq $mount.enabled true }}
            - name: frontend-{{ $mountName }}
              persistentVolumeClaim:
                claimName: {{ $.Release.Name }}-{{ $mountName }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
            - name: {{ .Release.Name }}-backup
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-backup
{{- end }}
