apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets-frontend
  labels:
    {{- include "frontend.release_labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.nginx.basicauth.enabled }}
  .htaccess: |
    {{ printf "%s:{PLAIN}%s" .Values.nginx.basicauth.credentials.username .Values.nginx.basicauth.credentials.password | b64enc }}
  {{- end }}

  {{- if .Values.signalsciences.enabled }}
  signalsciences_accesskeyid: {{ .Values.signalsciences.accesskeyid | b64enc | quote }}
  signalsciences_secretaccesskey: {{ .Values.signalsciences.secretaccesskey | b64enc | quote }}
  {{- end }}
