{{ if .Values.shell.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets-shell
  labels:
    {{- include "frontend.release_labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.shell.gitAuth.keyserver.username }}
  keyserver.username: "{{ .Values.shell.gitAuth.keyserver.username | b64enc }}"
  {{- end }}
  {{- if .Values.shell.gitAuth.keyserver.password }}
  keyserver.password: "{{ .Values.shell.gitAuth.keyserver.password | b64enc }}"
  {{- end }}
{{- end }}