{{- if .Values.varnish.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-varnish
  labels:
    {{- include "frontend.release_labels" . | nindent 4 }}
    service: varnish
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "frontend.release_selector_labels" . | nindent 6 }}
      service: varnish
  template:
    metadata:
      labels:
        {{- include "frontend.release_labels" . | nindent 8 }}
        service: varnish
        silta-ingress: allow
      annotations:
        # Recreate pod when the configMap or secret changes.
        varnish-cm-checksum: {{ include (print $.Template.BasePath "/varnish-configmap-vcl.yaml") . | sha256sum }}
        varnish-sec-checksum: {{ include (print $.Template.BasePath "/varnish-secret.yaml") . | sha256sum }}
    spec:
      enableServiceLinks: false
      containers:
      - name: varnish
        image: {{ .Values.varnish.image }}:{{ .Values.varnish.imageTag }}
        imagePullPolicy: {{ .Values.varnish.imagePullPolicy }}
        ports:
        - containerPort: 8080
          name: web
        - containerPort: 6082
          name: admin
        livenessProbe:
          tcpSocket:
            port: 8080
        env:
        - name: VARNISH_STORAGE_BACKEND
          value: {{ .Values.varnish.storageBackend | quote }}
        {{- if .Values.varnish.extraParams }}
        - name: VARNISH_EXTRA_PARAMS
          value: {{ .Values.varnish.extraParams | quote }}
        {{- end }}
        livenessProbe:
          exec:
            command: ["varnishadm", "-t", "1", "ping"]
        readinessProbe:
          exec:
            command: ["varnishadm", "-t", "1", "ping"]
        resources:
{{ .Values.varnish.resources | toYaml | indent 10 }}
        volumeMounts:
        - name: varnish-vcl
          mountPath: /etc/varnish/default.vcl
          subPath: default_vcl
          readOnly: true
        - name: varnish-vcl
          mountPath: /etc/varnish/includes/vcl_recv.vcl
          subPath: vcl_recv_vcl
          readOnly: true
        - name: varnish-vcl
          mountPath: /etc/varnish/includes/vcl_deliver.vcl
          subPath: vcl_deliver_vcl
          readOnly: true
        - name: varnish-vcl
          mountPath: /etc/varnish/includes/vcl_synth_500.vcl
          subPath: vcl_synth_500_vcl
          readOnly: true
        - name: varnish-secret
          mountPath: "/etc/varnish/secret"
          subPath: control_key
          readOnly: true
      volumes:
      - name: varnish-vcl
        configMap:
          name: {{ .Release.Name }}-varnish-vcl
      - name: varnish-secret
        secret:
          secretName: {{ .Release.Name }}-secrets-varnish
{{- end }}
